{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "n8n-template-gallery.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "n8n-template-gallery.name" . }}
    helm.sh/chart: {{ include "n8n-template-gallery.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
